### ISSUE TITLE
L&B notification interlogger segfaults without brokers

### ISSUE THREAD

**Issue by valtri** [CESNET/glite-lb#28]
When there are no brokers in /etc/glite-lb/msg.conf, glite-lb-notif-interlod won't start:

```
myriad2.zcu.cz systemd[1]: Starting gLite Logging and Bookkeeping notification interlogger...
myriad2.zcu.cz systemd[1]: Started gLite Logging and Bookkeeping notification interlogger.
myriad2.zcu.cz syslog[28493]: ERROR    CONTROL - Failed to load plugin activemq_cpp_plugin.so: plugin_init: broker uri not configured
myriad2.zcu.cz systemd[1]: glite-lb-notif-interlogd.service: main process exited, code=killed, status=11/SEGV
myriad2.zcu.cz systemd[1]: Unit glite-lb-notif-interlogd.service entered failed state.
```

**Comment by valtri** [comment]
Stacktrace:

```
#0  0x00007ffff04eed9c in OutputPlugin::getConnection ()
    at src/activemq_cpp_plugin.cpp:295
#1  0x00007ffff04eedd1 in OutputPlugin::connect (
    this=this@entry=0x7fffd8000d30, topic="grid.emi.cmstest27402")
    at src/activemq_cpp_plugin.cpp:93
#2  0x00007ffff04ef00e in event_queue_connect (eq=0x5555557947b0, 
    me=0x555555794980) at src/activemq_cpp_plugin.cpp:353
#3  0x000055555555f23a in queue_thread (q=0x5555557947b0)
    at src/queue_thread.c:205
#4  0x00007ffff7148f33 in start_thread (arg=0x7ffff7fda700)
    at pthread_create.c:309
#5  0x00007ffff6c72ded in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```
